// generated by stringer -type=KeyState; DO NOT EDIT

package input

import "fmt"

const _KeyState_name = "KeyReleasedKeyPressed"

var _KeyState_index = [...]uint8{0, 11, 21}

func (i KeyState) String() string {
	if i < 0 || i+1 >= KeyState(len(_KeyState_index)) {
		return fmt.Sprintf("KeyState(%d)", i)
	}
	return _KeyState_name[_KeyState_index[i]:_KeyState_index[i+1]]
}
